// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAl8J3bN_HouoA3EjRJ_Uks_dPNJiC7Tbs',
    appId: '1:656828723913:web:479177088b763b9f681318',
    messagingSenderId: '656828723913',
    projectId: 'test-database-81c9e',
    authDomain: 'test-database-81c9e.firebaseapp.com',
    storageBucket: 'test-database-81c9e.appspot.com',
    measurementId: 'G-B0EC5YTV1B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYpdIPfPRONZeIL94mdjDt7eBqUAazi7c',
    appId: '1:656828723913:android:346f11b2b1f24137681318',
    messagingSenderId: '656828723913',
    projectId: 'test-database-81c9e',
    storageBucket: 'test-database-81c9e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoKeagxEcWL80s4klU27TVgMM9jynUP1E',
    appId: '1:656828723913:ios:c0938a0632588369681318',
    messagingSenderId: '656828723913',
    projectId: 'test-database-81c9e',
    storageBucket: 'test-database-81c9e.appspot.com',
    iosBundleId: 'com.example.main',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoKeagxEcWL80s4klU27TVgMM9jynUP1E',
    appId: '1:656828723913:ios:8085e0c7c73167fb681318',
    messagingSenderId: '656828723913',
    projectId: 'test-database-81c9e',
    storageBucket: 'test-database-81c9e.appspot.com',
    iosBundleId: 'com.example.main.RunnerTests',
  );
}
